apiVersion: 1

contactPoints:
  - orgId: 1
    name: xrd-webhook
    receivers:
      - uid: xrd-webhook-receiver
        type: webhook
        disableResolveMessage: false
        settings:
          url: ${WEBHOOK_RECEIVER_URL}
          httpMethod: POST
